# Generated by Django 4.2 on 2026-06-28 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/", verbose_name="照片")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "approved",
                    models.BooleanField(default=True, verbose_name="审核通过"),
                ),
                (
                    "feed_earned",
                    models.BooleanField(default=False, verbose_name="已获得饲料奖励"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "社区照片",
                "verbose_name_plural": "社区照片",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Egg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laid_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="下蛋时间"),
                ),
                (
                    "collected",
                    models.BooleanField(default=False, verbose_name="是否已收集"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eggs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "鸭蛋",
                "verbose_name_plural": "鸭蛋",
                "ordering": ["-laid_at"],
            },
        ),
        migrations.CreateModel(
            name="DuckProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duck_name",
                    models.CharField(
                        default="Kris", max_length=20, verbose_name="鸭鸭名字"
                    ),
                ),
                (
                    "feed_grams",
                    models.IntegerField(default=0, verbose_name="剩余饲料(g)"),
                ),
                (
                    "feed_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="喂食开始时间"
                    ),
                ),
                (
                    "total_eggs",
                    models.IntegerField(default=0, verbose_name="累计收获鸭蛋"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duck_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "鸭鸭档案",
                "verbose_name_plural": "鸭鸭档案",
            },
        ),
    ]
