# Generated by Django 4.2 on 2026-06-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duckapp", "0002_comment_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="duckprofile",
            name="completed_feeds",
            field=models.IntegerField(default=0, verbose_name="已完成喂食次数(0-2)"),
        ),
    ]
