# Generated by Django 4.2 on 2026-06-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duckapp", "0003_duckprofile_completed_feeds"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["-is_pinned", "-uploaded_at"],
                "verbose_name": "社区照片",
                "verbose_name_plural": "社区照片",
            },
        ),
        migrations.AddField(
            model_name="photo",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="置顶"),
        ),
    ]
