# Generated by Django 5.2.9 on 2026-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duckapp", "0004_add_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="duckprofile",
            name="best_feed_streak_days",
            field=models.IntegerField(default=0, verbose_name="最长连续喂食天数"),
        ),
        migrations.AddField(
            model_name="duckprofile",
            name="feeding_streak_days",
            field=models.IntegerField(default=0, verbose_name="连续喂食天数"),
        ),
        migrations.AddField(
            model_name="duckprofile",
            name="last_feed_date",
            field=models.DateField(blank=True, null=True, verbose_name="上次喂食日期"),
        ),
        migrations.AddField(
            model_name="duckprofile",
            name="legendary_pity_days",
            field=models.IntegerField(default=0, verbose_name="传说蛋保底天数"),
        ),
        migrations.AddField(
            model_name="egg",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("common", "明湖暖蛋"),
                    ("rare", "星露蓝蛋"),
                    ("legendary", "金冠彩蛋"),
                ],
                default="common",
                max_length=20,
                verbose_name="稀有度",
            ),
        ),
    ]
