# Generated by Codex on 2026-07-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duckapp', '0006_duckprofile_feed_accelerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duckprofile',
            name='feed_accelerate_count',
        ),
        migrations.RemoveField(
            model_name='duckprofile',
            name='feed_accelerate_date',
        ),
    ]
