# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckapp', '0007_remove_duckprofile_feed_accelerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='duckprofile',
            name='feed_accelerate_count',
            field=models.IntegerField(default=0, verbose_name='今日加速次数'),
        ),
        migrations.AddField(
            model_name='duckprofile',
            name='feed_accelerate_date',
            field=models.DateField(blank=True, null=True, verbose_name='上次加速日期'),
        ),
    ]
