# Generated by Django 5.2.9 on 2026-07-03 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duckapp", "0008_duckprofile_feed_accelerate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="反馈内容")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="联系方式"
                    ),
                ),
                ("resolved", models.BooleanField(default=False, verbose_name="已处理")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="反馈时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "ordering": ["-created_at"],
            },
        ),
    ]
