# Generated by Django 4.2 on 2026-07-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duckapp", "0009_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duckprofile",
            name="duck_name",
            field=models.CharField(
                default="明湖鸭鸭", max_length=20, verbose_name="鸭鸭名字"
            ),
        ),
    ]
